server:
  port: 8082

get.http:
  url: http://localhost:8080/rest/employees
  readTimeout: 5000
  writeTimeout: 5000
  connectionTimeout: 5000

post.http:
  url: http://localhost:8080/rest/employees
  readTimeout: 5000
  writeTimeout: 5000
  connectionTimeout: 5000

client.ssl:
  trustStore: truststore.jks
  trustStorePassword: password
  keyStore: keystore.jks
  keyStorePassword: password
  type: jks

resilience4j:
  circuitbreaker:
    minimumNumberOfCalls: 10
    failureRateThreshold: 50
    permittedNumberOfCallsInHalfOpenState: 2
    waitDurationInOpenStateInSeconds: 60
    slidingWindowSize: 20
